### ISSUE TITLE
Seperate the attributes from the dataset Business 

### ISSUE THREAD

**Issue by asaarloos** [course-dprep/consumer-rating-insights-Yelp#69]
The previous code gives not a the values that are available in the dataset. 

In the mail is written with attributes we have with the values.

**Comment by lucia-ramos-dominguez** [comment]
Hi Hannes! Roshini tried to help us fix this but she suggested we loop you in as it is quite complex, can you maybe take  a look at this issue. Thank you 


"Dear Roshini,

I hope my email finds you well. We were trying to group the attributes but the code you provided us, does not fully provide what we wanted to have so we are missing a lot of data.
For example, in Ambience there are subcategories that have hipster, romantic, touristy etc. But now the code gives them as none or NA. There are more examples of it. In the attached file, you can have a better overview which attributes have the value true or false or which attributes are selected in a category.

We'll push an issue for you in Github as well so you can see the problem and since we have limited time it is really important that you come back to us next week so we can continue"   this is what we already explained to Roshini 

and the list of attributes 
![image](https://github.com/user-attachments/assets/8abfa6fe-60c8-4c76-b8de-709908c0936e)

**Comment by claudiavhoof** [comment]
af
